# File: cloudbuild.yaml
steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/minte-dev', '.' ]

    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/minte-dev']

    # deploy to Cloud Run, vars set in gitlab
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'minte-dev', '--image', 'gcr.io/$PROJECT_ID/minte-dev',
    '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY
